apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/valcenirh/k8s.git
    path: dlp
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}      
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd